server:
  port: 8082

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/product_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:India@123}

   
  jpa:
    hibernate:
      ddl-auto: validate 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1 # Instructs Flyway to assume V1 is already applied
    default-schema: public 
    locations: classpath:db/migration


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
